apiVersion: v1
kind: Service
metadata:
  name: lego-api-service
spec:
  clusterIP: 10.120.6.9
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31141
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: lego-api
  sessionAffinity: None
  type: LoadBalancer