apiVersion: v1
kind: Service
metadata:
  name: fer-api-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: fer-api
  sessionAffinity: None
  type: LoadBalancer