apiVersion: v1
kind: Service
metadata:
  name: lego-api-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5000
  selector:
    app: lego-api
  sessionAffinity: None
  type: LoadBalancer